config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#new'
  resources :tasks, except: [:edit, :update] do
    collection do
      get :search
    end
    resources :comments, only: [:create]
  end
  post   '/like/:task_id' , to: 'likes#like',   as: 'like'
  delete '/like/:task_id' , to: 'likes#unlike', as: 'unlike'

  devise_for :users
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 400 }
  
  belongs_to :user
  belongs_to :task
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :task, counter_cache: :likes_count
end

app/models/task.rb
class Task < ApplicationRecord
  validates :goal, presence: true, length: { maximum: 200 }
  validates :deadline, presence: true
  validates :name, presence: true
  validates :url, presence: true, length: { maximum: 300 }
  validates :image_url, presence: true, length: { maximum: 300 }
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tasks
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_tasks, through: :likes, source: :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  #deviseにusernameカラムを追加するためのストロングパラメーターを設定
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :username, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:content, :user_id, :task_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables

  def like
    like = current_user.likes.new(task_id: @task.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(task_id: @task.id)
    like.destroy
  end

  private

  def set_variables
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: :new
  before_action :correct_user, only: [:destroy]
  protect_from_forgery except: :search
  
  def index
    @tasks = Task.all.order('created_at DESC').page(params[:page]).per(5)
  end 
  
  def show
    @task = Task.find(params[:id])
    @comments = @task.comments
    @comment = Comment.new
  end
  
  def new
    @task = Task.new
    @tasks = Task.limit(3).order('created_at DESC') 
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:notice] = '目標が作成されました'
      redirect_to root_url
    else
      @tasks = Task.limit(5).order('created_at DESC') 
      flash.now[:alert] ='目標の作成に失敗しました'
      render :new
    end
  end
  
  def destroy
    @task.destroy
    flash[:notice] = '目標を削除しました'
    redirect_to root_url
  end
  
  
  def search
    @items = []

    @keyword = params[:keyword]
    if @keyword.present?
      results = RakutenWebService::Ichiba::Item.search({
        keyword: @keyword,
        imageFlag: 1,
        hits: 5,
      })

      results.each do |result|
        item = read(result)
        @items << item
      end
    end
  end
  
  
  private
  
  def task_params
    params.require(:task).permit(:goal, :deadline, :name, :url, :image_url)
  end
  
  def read(result)
    code = result['itemCode']
    name = result['itemName']
    url = result['itemUrl']
    image_url = result['mediumImageUrls'].first
    
    {
      code: code,
      name: name,
      url: url,
      image_url: image_url,
    }
  end
  
  def correct_user
    @task = Task.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order('created_at DESC').page(params[:page]).per(3)
    @like_tasks = @user.like_tasks.order('created_at DESC').page(params[:page]).per(3).uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2019 Sugita</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to '買う前に目標を！', root_path , class: "title" %></li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user.id) do %>
             <i class="far fa-user"></i> マイページ
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fas fa-check"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_rakuten.html.erb
  <%= form_tag :search_tasks, method: :get, remote: true do %>
  <%= text_field_tag 'keyword', params[:keyword] %>
  <%= submit_tag('商品検索') %>
  <% end %>
  <div id="Remote"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>買う前に目標を！</title>
    <meta name="description" content="ついつい何でもを買いすぎていませんか？欲しいものがあるなら買う前についでに目標を立てて達成しちゃおう！みんなで応援し合ってみんなで幸せに！そんなサービスができました。">
    <%= csrf_meta_tags %>
    
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
　　<!-- swiper CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/css/swiper.min.css">
    
    <!-- FontAwesome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    
    <!-- Animate.css -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css" rel="stylesheet">
    
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <!-- app/assets/javascripts -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Google jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    
    <div class="notice-space"> 
    <% if flash[:notice] %>
      <div class="notice animated bounce">
        <%= flash[:notice]%>
      </div>
    <% elsif flash[:alert] %>
      <div class="notice animated bounce">
        <%= flash[:alert]%>
      </div>
    <% end %>
    </div>
    
  
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
    <!-- swiper js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.1.6/js/swiper.min.js"></script>
  </body>
</html>

app/views/likes/_like.html.erb
<span class="like-link" id="like-link-<%= task.id %>">
  <% if current_user.likes.find_by(task_id: task.id) %>
    <%= link_to unlike_path(task.id), method: :delete, remote: true do %>
        <span class = "iine_button"><i class="fas fa-heart">いいね</i><%= task.likes.count %></span>
    <% end %>
  <% else %>
    <%= link_to like_path(task.id), method: :post, remote: true do %>
        <span class = "iine_button"><i class="far fa-heart">いいね！</i><%= task.likes.count %></span>
    <% end %>
  <% end %>
</span>

app/views/likes/like.js.erb
$("#like-link-<%= @task.id %>").html('<%= escape_javascript(render "likes/like", task: @task ) %>');

app/views/likes/unlike.js.erb
$("#like-link-<%= @task.id %>").html('<%= escape_javascript(render "likes/like", task: @task ) %>');

app/views/tasks/index.html.erb
<h1 style="text-align: center;">目標っていいよね</h1>
<% @tasks.each do |task| %>
<div class="Tasks">
  <div class="deadline"><%= task.deadline %>までに・・・</div>
  <div class="goal"><%= task.goal %></div>
  <div id="wrapper" class="product clearfix">
    <div class="korewokau">そしてこれを買う <i class="fas fa-cart-arrow-down"></i></div>
    <a href="<%= task.url %>" target="_blank">
      <div class="float-left"><img src="<%= task.image_url %>" alt="商品画像"></div>
      <div class="float-right"><%= task.name %></div>
    </a>
  </div>
  <div class="task-under">
  <%= render 'likes/like', task: task %>
  <%= link_to(task_path(task.id)) do %>
    <i class="far fa-comment"></i> コメントで応援する
  <% end %>
  <% if current_user == task.user %>
    <%= link_to "削除する", task_path(task.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger btn-xs' %>
  <% end %>
  <%= link_to(user_path(task.user)) do %>
  <i class="far fa-user"></i> <%= task.user.username %>
  <% end %>
  </div>
</div>
<% end %>

<center><%= paginate @tasks %></center>

<center><%= link_to 'Toppageへ戻る', root_url %></center>

app/views/tasks/new.html.erb
<!-- ▽▽▽ログインしているとき▽▽▽ -->
<% if user_signed_in? %>

<div class="swiper-container no_swipe">
  <div class="swiper-wrapper">
    
    <div class="swiper-slide form-wrapper">
      <div class="form-group">
          <h1 class="title-message">欲しいもののためなら、きっとできる。</h1>
          <div class="createTask">目標を設定する</div>
        </div>
    </div>
    
    <div class="swiper-slide" style="text-align:center; margin-top:15px;">
      <h1>欲しいものはなに？</h1>
      <div>商品を検索してクリックで選ぼう</div>
      <%= form_tag :search_tasks, method: :get, remote: true, class: "form-inline" do %>
      <%= text_field_tag 'keyword', params[:keyword], class: 'form-control search_box', style: 'width:300px; margin:0 auto;' %>
      <%= submit_tag '検索', class: 'createTask-button' %>
      <% end %>
      
      <div id="Remote"></div>
    
    <%= form_for (@task) do |f| %>
    <div class="choice-product-warrper">
    <%= f.label :name, '選んだもの' %>
    <%= f.text_field :name, class: 'form-control choice-product', readonly: true %>
    </div>
    
    <%= f.hidden_field :url %>
    <%= f.hidden_field :image_url %>
    <div class="createTask-next createTask-nextSearch">つぎに進む</div>
    </div>
      
    <div class="swiper-slide form-wrapper">
      <div class="form-group">
        <h1>何をやるの？</h1>
        <%= f.text_area :goal, class: 'form-control', placeholder: "エベレストに登りたい！(最大200文字)" %>
        <div class="createTask-next">つぎに進む</div>
      </div>
    </div>
    
    <div class="swiper-slide form-wrapper">
      <div class="form-group">
        <h1>いつまでにやるの？</h1>
        <%= f.date_field :deadline, class: 'form-control' %>
        <div class="createTask-next">つぎに進む</div>
      </div>
    </div>
    
    
    <div class="swiper-slide form-wrapper">
      <div class="form-group">
        <h1>さあ、やってみよう！</h1>
        <%= f.submit '目標を投稿', class: 'createTask' %>
      <% end %>
      </div>
    </div>
  
    
  </div>
  
  <!-- ページネーションボタン-->
  <div class="swiper-pagination"></div>
  <!-- ナビゲーションボタン-->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>

</div>

<h1 style="text-align:center;">最近投稿された目標</h1>
<% @tasks.each do |task| %>
<div class="Tasks">
  <div class="deadline"><%= task.deadline %>までに・・・</div>
  <%= link_to(task_path(task.id), class: "go-show") do %>
  <div class="goal"><%= task.goal %></div>
  <% end %>
  <div id="wrapper" class="product clearfix">
    <div class="korewokau">そしてこれを買う <i class="fas fa-cart-arrow-down"></i></div>
    <a href="<%= task.url %>" target="_blank">
      <div class="float-left"><img src="<%= task.image_url %>" alt="商品画像"></div>
      <div class="float-right"><%= task.name %></div>
    </a>
  </div>
  <div class="task-under">
  <%= render 'likes/like', task: task %>
  <%= link_to(task_path(task.id)) do %>
    <i class="far fa-comment"></i> コメントで応援する
  <% end %>
  <% if current_user == task.user %>
    <%= link_to "削除する", task_path(task.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger btn-xs' %>
  <% end %>
  <%= link_to(user_path(task.user)) do %>
  <i class="far fa-user"></i> <%= task.user.username %>
  <% end %>
  </div>
</div>
<% end %>
<div style="text-align:center;font-size: 130%;"><i class="far fa-arrow-alt-circle-right"></i> <%= link_to 'みんなの目標をもっとみる', tasks_path %></div>



<!-- ▽▽▽ログインしていないとき▽▽▽ -->
<% else %> 
  <div><img src="/images/topimage.png" alt="欲しいもののためならがんばれる。(画像)" class="top-image"></div>
  <div style="text-align:center;">
  <%= link_to new_user_registration_path do %>
    <div class="base_btn base_btn-top">新規登録</div>
  <% end %>
  <%= link_to user_session_path do %>
    <div>>ログインはこちらから</div>
  <% end %>
  </div>

<h1 style="margin:100px 0px 30px;"><i class="far fa-flag"></i> 最近はこんな目標が立てられました</h1>
<% @tasks.each do |task| %>
<div class="Tasks">
  <div class="deadline"><%= task.deadline %>までに・・・</div>
  <div class="goal"><%= task.goal %></div>
  <div id="wrapper" class="product clearfix">
    <div class="korewokau">そしてこれを買う <i class="fas fa-cart-arrow-down"></i></div>
    <a href="<%= task.url %>" target="_blank">
      <div class="float-left"><img src="<%= task.image_url %>" alt="商品画像"></div>
      <div class="float-right"><%= task.name %></div>
    </a>
  </div>
  <div style="text-align:right; margin-right: 8px;">
  <i class="far fa-heart"></i> いいね<%= task.likes.count %>
  <i class="far fa-user"></i> <%= task.user.username %>
  </div>
</div>
<% end %>

<% end %>

app/views/tasks/search.js.erb
$('#Remote').empty();

<% @items.each do |key, value| %>
  $('#Remote').append("<img src='<%= key[:image_url] %>' alt='画像' class ='product-image'><p style='background-color: grey; display:none;'><%= key[:name] %>,%¥<%= key[:url] %>,%¥<%= key[:image_url] %></p>")
<% end %>

$("#Remote img").on("click", function(){

  $('.choice-product-warrper').css('display', 'block');
  $('.createTask-nextSearch').css('display', 'inline-block');

  var str = $(this).next('p').html();
  str.toString();
  var result = str.split(',%¥');

  name = result[0]
  url = result[1]
  image_url = result[2]

    $('#task_name').val(name);
    $('#task_url').val(url);
    $('#task_image_url').val(image_url);
});

app/views/tasks/show.html.erb
<div class="Tasks">
  <div class="deadline"><%= @task.deadline %>までに・・・</div>
  <div class="goal"><%= @task.goal %></div>
  <div id="wrapper" class="product clearfix">
    <div class="korewokau">そしてこれを買う <i class="fas fa-cart-arrow-down"></i></div>
    <a href="<%= @task.url %>" target="_blank">
      <div class="float-left"><img src="<%= @task.image_url %>" alt="商品画像"></div>
      <div class="float-right"><%= @task.name %></div>
    </a>
  </div>
  <div class="task-under">
  <%= render 'likes/like', task: @task %>
  <% if current_user == @task.user %>
    <%= link_to "削除する", task_path(@task.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger btn-xs' %>
  <% end %>
  <%= link_to(user_path(@task.user)) do %>
    <i class="far fa-user"></i> <%= @task.user.username %>
  <% end %>
  </div>
</div>


<%= form_for [@task, @comment],  html: {class: 'comment-form-wrapper'} do |f| %>
  <%= f.text_field :content, class: 'form-control comment-form' %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :task_id, :value => @task.id %>
  <%= f.submit 'コメントする', class: "base_btn comment-btn"  %>
<% end %>

<% if @comments.present? %>
<h2 style="text-align:center; margin: 60px 0px 30px;"><i class="far fa-comments"></i> コメント</h2>
<% @comments.each do |c| %>
  <div class="comment-index">
     <div class="comment-user">
         <%= link_to(user_path(c.user)) do %>
             <i class="far fa-user"></i> <%= c.user.username %>
         <% end %>
     <div class="comment-content"><%= c.content %></div>
     </div>
  </div>
<% end %>
<% end %>


<center style="margin-top: 50px;"><%= link_to 'Toppageへ戻る', root_url %></center>

app/views/users/show.html.erb
<h1><i class="far fa-check-square"></i> <%= @user.username %>がの立てた目標</h1>

<% @tasks.each do |task| %>
<div class="Tasks">
  <div class="deadline"><%= task.deadline %>までに・・・</div>
  <div class="goal"><%= task.goal %></div>
  <div id="wrapper" class="product clearfix">
    <div class="korewokau">そしてこれを買う <i class="fas fa-cart-arrow-down"></i></div>
    <a href="<%= task.url %>" target="_blank">
      <div class="float-left"><img src="<%= task.image_url %>" alt="商品画像"></div>
      <div class="float-right"><%= task.name %></div>
    </a>
  </div>
  <div class="task-under">
  <%= render 'likes/like', task: task %>
  <%= link_to(task_path(task.id)) do %>
    <i class="far fa-comment"></i> コメントで応援する
  <% end %>
  <% if current_user == task.user %>
    <%= link_to "削除する", task_path(task.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger btn-xs' %>
  <% end %>
  </div>
</div>
<% end %>
<center><%= paginate @tasks %></center>

<h1><i class="far fa-heart"></i> <%= @user.username %>がいいねした目標</h1>

<% @like_tasks.each do |task| %>
<div class="Tasks">
  <div class="deadline"><%= task.deadline %>までに・・・</div>
  <div class="goal"><%= task.goal %></div>
  <div id="wrapper" class="product clearfix">
    <div class="korewokau">そしてこれを買う <i class="fas fa-cart-arrow-down"></i></div>
    <a href="<%= task.url %>" target="_blank">
      <div class="float-left"><img src="<%= task.image_url %>" alt="商品画像"></div>
      <div class="float-right"><%= task.name %></div>
    </a>
  </div>
  <div class="task-under">
  <%= render 'likes/like', task: task %>
  <%= link_to(task_path(task.id)) do %>
    <i class="far fa-comment"></i> コメントで応援する
  <% end %>
  <% if current_user == task.user %>
    <%= link_to "削除する", task_path(task.id), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger btn-xs' %>
  <% end %>
  </div>
</div>
<% end %>
<center><%= paginate @like_tasks %></center>

<center><%= link_to 'Toppageへ戻る', root_url %></center>